mysiteproject/mysiteproject/urls.py
from django.contrib import admin
from django.urls import path, include
from usersapp import views
#from django.contrib import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('info/',views.info,name='info'),
    path('usersapp/',include('usersapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('create/',views.u_create,name='u_create'),
    path('articles/',views.article_list,name='article_list'),    
    path('edit/<int:id>', views.edit),      
    path('update/<int:id>', views.update),      
    path('delete/<int:id>', views.destroy),
    
]

mysiteproject/usersapp/urls.py
from django.urls import path
from usersapp import views


app_name='usersapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('u_login/',views.u_login,name='u_login'),
    path('home_page/',views.home_page,name='home_page'),   
    path('articles/',views.articles,name='articles'), 
    path('create_user/',views.create_user,name='create_user'),    
    path('info_view/',views.info_view,name='info_view'),
    
]

mysiteproject/usersapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def _str_(self):
        return self.user.username

class Article(models.Model):
    user=models.CharField(max_length=100)
    title =models.CharField(max_length=100)
    slug =models.SlugField()
    body =models.TextField()
    date =models.DateField(auto_now_add=True)

    # def __str__(self):
    #     return self.title

    # def snippet(self):
    #     return self.body[:50] + '...'
class Comment(models.Model):
    commenter=models.CharField(max_length=50)
    body=models.TextField()
    

    def __str__(self):
        return self.body

mysiteproject/usersapp/forms.py
from django import forms
from django.contrib.auth.models import User
from usersapp.models import UserProfileInfo,Article
from django.forms import fields



class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

# class CommentForm(forms.ModelForm):
#     commenter=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Your name'}))
#     body=forms.CharField(max_length=100,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Comment here','rows':3})) 
#     class Meta:
#         model=Comments
#         fields=['commenter','body']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

mysiteproject/usersapp/views.py
from django.shortcuts import render, redirect
from .forms import UserEditForm, UserForm,UserProfileInfoForm
from usersapp.models import Article,Comment


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages



# Create your views here.
def index(request):
    return render(request,'usersapp/index.html')

def special(request):
    return render(request,'usersapp/home_page.html')

def article_list(request):
    articles=Article.objects.all().order_by('date')
    return render(request,'usersapp/article_list.html',{'Article':articles})

def articles(request):
    art=Article.objects.all().order_by('date')
    return render(request,'usersapp/articles.html',{'Article':art})

def home_page(request):
    return render(request,'usersapp/home_page.html')

def info(request):
    comment=Comment.objects.all()
    return render(request,'usersapp/info.html',{'Comment':comment})

def info_view(request):
    if request.method=='POST':
        if request.POST.get('commenter') and request.POST.get('body') :
            com=Comment()
            com.commenter=request.POST.get('commenter')
            com.body=request.POST.get('body')
            com.save()
   
    return redirect('/info')

#logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))




def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user


            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            
            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
   
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm

    return render(request,'usersapp/user_register.html',
                            {'user_form':user_form,
                               'profile_form':profile_form,
                               'registered':registered})


def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('special'))

            else:
                return HttpResponse("ACCOUNTS NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request,'usersapp/user_login.html',{})

def u_login(request):
    return render(request, 'usersapp/user_login.html')

# def registration(request):
#     registered=False
#     if request.method == 'POST':
        
#     else:
#         return UserForm()
#     return render(request, 'usersapp/user_register.html',context={'user_form':user_form,
#                                'profile_form':profile_form,
#                                'registered':registered})

def u_create(request):
    return render(request, 'usersapp/Create.html')


def create_user(request):
    if request.method=='POST':
        if request.POST.get('user') and request.POST.get('title') and request.POST.get('slug') and request.POST.get('body') and request.POST.get('date'):
            saveus=Article()
            saveus.user=request.POST.get('user')
            saveus.title=request.POST.get('title')
            saveus.slug=request.POST.get('slug')
            saveus.body=request.POST.get('body')
            saveus.date=request.POST.get('date')
            saveus.save()
            
            return HttpResponseRedirect(reverse('article_list'))

        else:
            return render(request,'usersapp/Create.html')

# def user_edit(request,id):
#     getuserarticles=Article.objects.get(id=id)
#     return render(request,'edit.html',{'Article':getuserarticles})

# def user_update(request,id):
#     user_update=Article.objects.get(id=id)
#     form=UserForm(request.POST,instance=user_update)

#     if form.is_valid():
#         form.save()
#         messages.success(request,"The user record is updated successfully..!")
#         return render(request,"edit.html",{"Article":user_update})
def edit(request, id):  
    article = Article.objects.get(id=id)  
    return render(request,'usersapp/edit.html', {'article':article})  
    
def update(request, id):  
    article = Article.objects.get(id=id) 
    form = UserEditForm(request.POST, instance = article)  
    if form.is_valid():  
        form.save()  
        return redirect("/articles")  
    return render(request, 'usersapp/edit.html', {'article':article})  

def destroy(request, id):  
    article = Article.objects.get(id=id) 
    article.delete()  
    return redirect("/articles")

mysiteproject/templates/usersapp/Create.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>create</title>
</head>
<body id="bg" style="background-image: url('{% static  "images/futuristic.jpg" %}');" >
    <header>
        <a class= "p-2 text-white" href="{% url 'special' %}"><b>Home</b></a>
    </header>
<center>
    
        <h3 style="color:white"><b>Add New User Record</b></h3>
        <hr/>  
        <form action="{% url 'usersapp:create_user' %}" method="POST" >
            {% csrf_token     %}
         <table border="1">
        <tr>
         <td style="color:white">User</td>
         <td><input type="text" placeholder="User's name .." name="user"></td>
         </tr>

        <tr>
         <td style="color:white">Title</td>
         <td><input type="text" placeholder="Title .." name="title"></td>
        </tr>

        <tr>
            <td style="color:white">Slug</td>
            <td><input type="text" placeholder="Slug .." name="slug"></td>
        </tr>
    
        <tr>
            <td style="color:white">Body</td>
            <td><input type="text" placeholder="Body .." name="body"></td>
        </tr>

        <tr>
            <td style="color:white">Date</td>
            <td><input type="text" placeholder="Date" name="date"></td>
        </tr>

    </table>

    <input type="submit" value="Insert Record"/>
    
   
    <hr/>
    {% if messages %}

     {% for result in messages %}

    <b style="color:green">{{result}}</b>

    {% endfor %}
    {% endif %}


</form>    
<a href="{% url 'article_list' %}" style="color:white;background-color: blue;font-size: large;"><b>Article list </b></a>
</center>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

mysiteproject/templates/usersapp/base.html
{% load static %}
{% block content %}

<!DOCTYPE html>

<html lang="en">
   <head>

     <meta charset="utf-8">
     <title>My 4IR Web</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>

     <!-- <style type="text/css">
        
      @media (min-width: 768px) {
     html {
          font-size: 16px;
        }
      }
      
      .container {
        max-width: 960px;
      }
      
      .pricing-header {
        max-width: 700px;
      }
      
      .card-deck .card {
        min-width: 220px;
      } -->

    </style> 
    <body id="bg" style="background-image: url('{% static  "images/futuristic.jpg" %}');" >
      <header>
                {%  if request.user.is_authenticated %}
                <p style="color:white">Hello, {{ request.user.username}}</p>

                {% endif %}
            
              <div>   <nav class="my-2 my-md-0 mr-md-3"  >
                {%  if request.user.is_authenticated %}
                <a class= "p-2 text-white" href="{% url 'admin:index' %}">Admin</a>
                <a class= "p-2 text-white" href="{%  url 'usersapp:u_login' %}">Login</a>
                {% endif %}
            
              <a class= "p-2 text-white" href="{% url 'index' %}">Home</a>
              <!-- <a class= "p-2 text-white" href="{% url 'usersapp:articles' %}">Articles</a> -->
              <a class= "p-2 text-white" href="{% url 'admin:index' %}">Admin</a>
              
              
                    
              {%  if user.is_authenticated %}
              <a class= "p-2 text-white" href="{% url 'logout' %}">Logout</a>

              {% else %}
              <a class= "p-2 text-white" href="{%  url 'usersapp:u_login' %}">Login</a>
              <a class="btn btn-outline-primary" href="{% url 'usersapp:register' %}">Register</a>      
              {% endif %}

        </nav>
      </div>
    </header>
  <br>
  <br>
  <section>
    <div class="content">
      <a href="{% url 'info' %}"  class="logo" ><b>4IR</b></a>
      <p >Our interest focuses on the impact of 4IR in the world today.</p>
      <p style="color:white"><b>HAVE YOUR SAY..!</b></p>
      <p> Register on our website Now!</p>
      <p>Login and Create Your Very Own Article on 4IR</p>
      
      <a href="{% url 'usersapp:articles' %}" class="btn">Articles</a>
     </div>
  <div class="container"></div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"
integrity="sha512-z4OUqw38qNLpn1libAN9BsoDx6nbNFio5lA6CuTp9NlK83b89hgyCVq+N5FdBJptINztxn1Z3SaKSKUS5UP60Q==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
   let container=document.querySelector('.container');
   for(let i=1;i<=16;i++){
    let dot = document.createElement('div');
    dot.classList.add('element');
    container.appendChild(dot);
   }
 let dotAll=document.querySelectorAll('.element');
 let animation=anime.timeline({
 targets:dotAll,
 easing: 'easeInOutExpo',
 loop:true,
 delay:anime.stagger(16,{grid:[4,4],from:'center'})
 })
 animation
 .add({
   rotateZ:180,
   translateY:anime.stagger(-5,{grid:[4,4],from:'center',axis:'y'}),
   translateX:anime.stagger(-5,{grid:[4,4],from:'center',axis:'x'}),
   opacity:1,
 
 })
 .add({
   borderRadius:50,
 
 })
 .add({
   scale:0.2,
   opacity:0.2,
 
 })
 .add({
   rotateZ:180,
   translateY:anime.stagger(0,{grid:[4,4],from:'center',axis:'y'}),
   translateX:anime.stagger(0,{grid:[4,4],from:'center',axis:'x'}),
   opacity:1,
 
 })
 .add({
    scale:1,
    borderRadius:0,
 })
 .add({
    rotateZ:-90,
 })
 
 
    </script>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{%  endblock %}
</html>

mysiteproject/templates/usersapp/home_page.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>my 4IR web</title>
</head>
<body id="bg" style="background-image: url('{% static  "images/futuristic.jpg" %}');" >
    <header>
        {%  if request.user.is_authenticated %}
        <p style="color:white">Hello, {{ request.user.username }}</p>

        {% endif %}
    
      <div>   <nav class="my-2 my-md-0 mr-md-3"  >
        
      
      <a class= "p-2 text-white" href="{% url 'special' %}">Home</a>
      
            
      {%  if user.is_authenticated %}
      <a class= "p-2 text-white" href="{% url 'u_create' %}">Add-Article</a>
      <a class= "p-2 text-white" href="{% url 'logout' %}">Logout</a>
      {% endif %}

        </nav>
        </div>
        </header>
          



    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

mysiteproject/templates/usersapp/index.html
{%  extends "usersapp/base.html"   %}

{%  load static  %}

mysiteproject/templates/usersapp/info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>about4IR</title>
  
</head>
<body style="background-image: url('{% static  "images/futuristic.jpg" %}');">
    <header>
        <a href="{% url 'index' %}" class="btn" style="color:white"><b>Home</b></a>
    </header>
    
        <center>
        <h1 style="color:white"><b>About 4IR</b></h1>
    </center>



<center>
    <br>
    <br>
 <p style="color:white">The Fourth Industrial Revolution (4IR) refers to our current period of rapid technological 
    growth which is fundamentally changing the way we live. By drawing on a multitude of advanced 
    technologies, 4IR blurs the lines between the physical, digital, and biological worlds.</p>
<p style="color:white">The Fourth Industrial Revolution is about more than just technology-driven change; it is an opportunity to
     help everyone, including leaders, policy-makers and people from all income groups and nations, to harness 
     converging technologies in order to create an inclusive, human-centred future.</p>
</center>
<div class="row">
        
    <div class="col" ><p id="human"><img src="{% static 'images/origin.jpg' %}"  class="img-thumbnail" ></div>
    <div class="col" ><p id="human"><img src="{% static 'images/edu3.jpg' %}"    class="img-thumbnail"></div>
    <div class="col" ><p id="human"><img src="{% static 'images/heal4.jpg' %}"   class="img-thumbnail"></div>
    <div class="col" ><p id="human"><img src="{% static 'images/motion.jpg' %}"  class="img-thumbnail"></div>   
  </div>
  <div class="row">
    <div class="col"><p style="color:white">Attachment, empathy, sensation seeking and engagement are the many varied qualities 
        in humans that shape our relationships with robots, Robots contribute to that relationship 
        through their independence and emotionally interactive designs.</p></div>

    <div class="col" ><p style="color:white">The Fourth Industrial Revolution impacts in evolving teaching strategies so as to unlock 
      an individual student potential and prepare students with the skills needed to shape the future through innovation 
      supported by technology.
      Today’s students must be able to not only adapt to the 4th Industrial Revolution but be positioned to shape
      themselves through creative problem solving and open thinking, such will
       also advance them to make the most of applying technology in new ways.</p></div>

      <div class="col" style="text-align: right;color:white">Virtual reality is increasingly being used to train patients and assist
        with pain management. The use of both AR and VR have been proven to have positive impacts on immersive learning  and 
       healing across the healthcare spectrum. Medical assistants can help patients recover from strokes while they are anywhere in
      the world by using a combination of robotics and virtual-reality devices.
    </div>
    <div class="col"><p style="color:white">Latest innovations in robotics have shown
        that robots can be a part of human lives. Robots are assisting humans in every type of business, 
        contributing to higher quality products with shorter downtime.</p>
</div>
  </div>

<br>
<br>

<form action="{% url 'usersapp:info_view' %}" method="POST" >
  {% csrf_token     %}





  <h5 style="color:blue"><b>Was the above info helpful?</b><h5> 
   <p style="color:white"> Comment down below..!</p>
  <input type="text" placeholder="Commenter ..." name="commenter">

  <!-- </h3 style="color:white">Body</h3> -->
  <input type="text" placeholder="Body .." name="body">

  <input style="background-color: blue;color:antiquewhite" type="submit" value="Submit"/>


</form>    

<br>
<br>
<div style="color:white">{% for info in Comment %}
    <div>
      <p>{{ info.commenter }}--
      {{ info.body }}</p><br>
    </div>
    {% endfor %}

  </div>






</body  >
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

mysiteproject/templates/usersapp/user_login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>login</title>
</head>
<body id="bg" style="background-image: url('{% static  "images/futuristic.jpg" %}');">
    <header>
        <a href="{% url 'index' %}" class="btn" style="color:white"><b>Home</b></a>
    </header>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
    <div >
        <h1 style="color:white">Please Login</h1>
    
        <form action="{% url 'usersapp:user_login' %}" method="POST">
    
            {% csrf_token  %} 
            <label for="username" style="color:white">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            
    
            <label for="password" style="color:white">Password:</label>
            <input type="password" name="password" >
    
    
            <input style="background-color:blue;color:white;font-size: large;" type="submit" name="" value="Login" >
        </form>
    
    
    
    
    
    
    
    </div>
</center>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

mysiteproject/templates/usersapp/user_register.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register</title>
</head>
<body id="bg" style="background-image: url('{% static  "images/futuristic.jpg" %}');">
    
<div class="jumbotron">
    {%  if registered %}
        <h1  style="color:white">Thank you for registering</h1>
        <a href="{% url 'index' %}" class="btn" style="color:white"><b>Home</b></a>

        <a class= "p-2 text-white" style="color:white" href="{%  url 'usersapp:u_login' %}"><b>Login</b></a>

    {% else %}
        <a href="{% url 'index' %}" class="btn" style="color:white"><b>Home</b></a>
        <h1 style="color:white">Register here</h1>
        <h3 style="color:white" >TFill out the form:</h3>
        

        <form  style="color:white" enctype="multipart/form-data"  method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input style="color:white;background-color: blue;" type="submit" name=""  value="Register">


        </form>

    {%  endif  %}

</div>
</body>
</html>